#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestaoOficina.Api
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
    using Newtonsoft.Json;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaOficina")]
	public partial class SistemaOficinaDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertMarcacoe(Marcacoe instance);
    partial void UpdateMarcacoe(Marcacoe instance);
    partial void DeleteMarcacoe(Marcacoe instance);
    partial void InsertMecanico(Mecanico instance);
    partial void UpdateMecanico(Mecanico instance);
    partial void DeleteMecanico(Mecanico instance);
    partial void InsertReparacoe(Reparacoe instance);
    partial void UpdateReparacoe(Reparacoe instance);
    partial void DeleteReparacoe(Reparacoe instance);
    partial void InsertReparacoesMecanico(ReparacoesMecanico instance);
    partial void UpdateReparacoesMecanico(ReparacoesMecanico instance);
    partial void DeleteReparacoesMecanico(ReparacoesMecanico instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    #endregion
		
		public SistemaOficinaDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaOficinaDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaOficinaDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SistemaOficinaDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Marcacoe> Marcacoes
		{
			get
			{
				return this.GetTable<Marcacoe>();
			}
		}
		
		public System.Data.Linq.Table<Mecanico> Mecanicos
		{
			get
			{
				return this.GetTable<Mecanico>();
			}
		}
		
		public System.Data.Linq.Table<Reparacoe> Reparacoes
		{
			get
			{
				return this.GetTable<Reparacoe>();
			}
		}
		
		public System.Data.Linq.Table<ReparacoesMecanico> ReparacoesMecanicos
		{
			get
			{
				return this.GetTable<ReparacoesMecanico>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculos
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private string _Apelido;
		
		private string _Contacto;
		
		private string _NIF;
		
		private string _Email;
		
		private EntitySet<Marcacoe> _Marcacoes;
		
		private EntitySet<Veiculo> _Veiculos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnApelidoChanging(string value);
    partial void OnApelidoChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnNIFChanging(string value);
    partial void OnNIFChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Cliente()
		{
			this._Marcacoes = new EntitySet<Marcacoe>(new Action<Marcacoe>(this.attach_Marcacoes), new Action<Marcacoe>(this.detach_Marcacoes));
			this._Veiculos = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculos), new Action<Veiculo>(this.detach_Veiculos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apelido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apelido
		{
			get
			{
				return this._Apelido;
			}
			set
			{
				if ((this._Apelido != value))
				{
					this.OnApelidoChanging(value);
					this.SendPropertyChanging();
					this._Apelido = value;
					this.SendPropertyChanged("Apelido");
					this.OnApelidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIF", DbType="NVarChar(9)")]
		public string NIF
		{
			get
			{
				return this._NIF;
			}
			set
			{
				if ((this._NIF != value))
				{
					this.OnNIFChanging(value);
					this.SendPropertyChanging();
					this._NIF = value;
					this.SendPropertyChanged("NIF");
					this.OnNIFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}

        //Não mostrar as Marcações e Veículos do Cliente.
        [JsonIgnore]

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Marcacoe", Storage="_Marcacoes", ThisKey="Id", OtherKey="IdCliente")]
		public EntitySet<Marcacoe> Marcacoes
		{
			get
			{
				return this._Marcacoes;
			}
			set
			{
				this._Marcacoes.Assign(value);
			}
		}
        //Não mostrar as Marcações e Veículos do Cliente.
        [JsonIgnore]
        [global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Veiculo", Storage="_Veiculos", ThisKey="Id", OtherKey="IdCliente")]
		public EntitySet<Veiculo> Veiculos
		{
			get
			{
				return this._Veiculos;
			}
			set
			{
				this._Veiculos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marcacoes")]
	public partial class Marcacoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdCliente;
		
		private int _IdVeiculo;
		
		private int _IdMecanico;
		
		private string _TipoServico;
		
		private System.DateTime _DataHora;
		
		private string _Estado;
		
		private EntitySet<Reparacoe> _Reparacoes;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Mecanico> _Mecanico;
		
		private EntityRef<Veiculo> _Veiculo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnIdVeiculoChanging(int value);
    partial void OnIdVeiculoChanged();
    partial void OnIdMecanicoChanging(int value);
    partial void OnIdMecanicoChanged();
    partial void OnTipoServicoChanging(string value);
    partial void OnTipoServicoChanged();
    partial void OnDataHoraChanging(System.DateTime value);
    partial void OnDataHoraChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public Marcacoe()
		{
			this._Reparacoes = new EntitySet<Reparacoe>(new Action<Reparacoe>(this.attach_Reparacoes), new Action<Reparacoe>(this.detach_Reparacoes));
			this._Cliente = default(EntityRef<Cliente>);
			this._Mecanico = default(EntityRef<Mecanico>);
			this._Veiculo = default(EntityRef<Veiculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVeiculo", DbType="Int NOT NULL")]
		public int IdVeiculo
		{
			get
			{
				return this._IdVeiculo;
			}
			set
			{
				if ((this._IdVeiculo != value))
				{
					if (this._Veiculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVeiculoChanging(value);
					this.SendPropertyChanging();
					this._IdVeiculo = value;
					this.SendPropertyChanged("IdVeiculo");
					this.OnIdVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMecanico", DbType="Int NOT NULL")]
		public int IdMecanico
		{
			get
			{
				return this._IdMecanico;
			}
			set
			{
				if ((this._IdMecanico != value))
				{
					if (this._Mecanico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMecanicoChanging(value);
					this.SendPropertyChanging();
					this._IdMecanico = value;
					this.SendPropertyChanged("IdMecanico");
					this.OnIdMecanicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoServico", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoServico
		{
			get
			{
				return this._TipoServico;
			}
			set
			{
				if ((this._TipoServico != value))
				{
					this.OnTipoServicoChanging(value);
					this.SendPropertyChanging();
					this._TipoServico = value;
					this.SendPropertyChanged("TipoServico");
					this.OnTipoServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataHora", DbType="DateTime NOT NULL")]
		public System.DateTime DataHora
		{
			get
			{
				return this._DataHora;
			}
			set
			{
				if ((this._DataHora != value))
				{
					this.OnDataHoraChanging(value);
					this.SendPropertyChanging();
					this._DataHora = value;
					this.SendPropertyChanged("DataHora");
					this.OnDataHoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marcacoe_Reparacoe", Storage="_Reparacoes", ThisKey="Id", OtherKey="IdMarcacao")]
		public EntitySet<Reparacoe> Reparacoes
		{
			get
			{
				return this._Reparacoes;
			}
			set
			{
				this._Reparacoes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Marcacoe", Storage="_Cliente", ThisKey="IdCliente", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Marcacoes.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Marcacoes.Add(this);
						this._IdCliente = value.Id;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mecanico_Marcacoe", Storage="_Mecanico", ThisKey="IdMecanico", OtherKey="Id", IsForeignKey=true)]
		public Mecanico Mecanico
		{
			get
			{
				return this._Mecanico.Entity;
			}
			set
			{
				Mecanico previousValue = this._Mecanico.Entity;
				if (((previousValue != value) 
							|| (this._Mecanico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mecanico.Entity = null;
						previousValue.Marcacoes.Remove(this);
					}
					this._Mecanico.Entity = value;
					if ((value != null))
					{
						value.Marcacoes.Add(this);
						this._IdMecanico = value.Id;
					}
					else
					{
						this._IdMecanico = default(int);
					}
					this.SendPropertyChanged("Mecanico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_Marcacoe", Storage="_Veiculo", ThisKey="IdVeiculo", OtherKey="Id", IsForeignKey=true)]
		public Veiculo Veiculo
		{
			get
			{
				return this._Veiculo.Entity;
			}
			set
			{
				Veiculo previousValue = this._Veiculo.Entity;
				if (((previousValue != value) 
							|| (this._Veiculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Veiculo.Entity = null;
						previousValue.Marcacoes.Remove(this);
					}
					this._Veiculo.Entity = value;
					if ((value != null))
					{
						value.Marcacoes.Add(this);
						this._IdVeiculo = value.Id;
					}
					else
					{
						this._IdVeiculo = default(int);
					}
					this.SendPropertyChanged("Veiculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reparacoes(Reparacoe entity)
		{
			this.SendPropertyChanging();
			entity.Marcacoe = this;
		}
		
		private void detach_Reparacoes(Reparacoe entity)
		{
			this.SendPropertyChanging();
			entity.Marcacoe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mecanicos")]
	public partial class Mecanico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private string _Especialidade;
		
		private string _Horario;
		
		private string _Contacto;
		
		private bool _Ativo;
		
		private EntitySet<Marcacoe> _Marcacoes;
		
		private EntitySet<ReparacoesMecanico> _ReparacoesMecanicos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEspecialidadeChanging(string value);
    partial void OnEspecialidadeChanged();
    partial void OnHorarioChanging(string value);
    partial void OnHorarioChanged();
    partial void OnContactoChanging(string value);
    partial void OnContactoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    #endregion
		
		public Mecanico()
		{
			this._Marcacoes = new EntitySet<Marcacoe>(new Action<Marcacoe>(this.attach_Marcacoes), new Action<Marcacoe>(this.detach_Marcacoes));
			this._ReparacoesMecanicos = new EntitySet<ReparacoesMecanico>(new Action<ReparacoesMecanico>(this.attach_ReparacoesMecanicos), new Action<ReparacoesMecanico>(this.detach_ReparacoesMecanicos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidade", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Especialidade
		{
			get
			{
				return this._Especialidade;
			}
			set
			{
				if ((this._Especialidade != value))
				{
					this.OnEspecialidadeChanging(value);
					this.SendPropertyChanging();
					this._Especialidade = value;
					this.SendPropertyChanged("Especialidade");
					this.OnEspecialidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="NVarChar(50)")]
		public string Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this.OnContactoChanging(value);
					this.SendPropertyChanging();
					this._Contacto = value;
					this.SendPropertyChanged("Contacto");
					this.OnContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mecanico_Marcacoe", Storage="_Marcacoes", ThisKey="Id", OtherKey="IdMecanico")]
		public EntitySet<Marcacoe> Marcacoes
		{
			get
			{
				return this._Marcacoes;
			}
			set
			{
				this._Marcacoes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mecanico_ReparacoesMecanico", Storage="_ReparacoesMecanicos", ThisKey="Id", OtherKey="IdMecanico")]
		public EntitySet<ReparacoesMecanico> ReparacoesMecanicos
		{
			get
			{
				return this._ReparacoesMecanicos;
			}
			set
			{
				this._ReparacoesMecanicos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Mecanico = this;
		}
		
		private void detach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Mecanico = null;
		}
		
		private void attach_ReparacoesMecanicos(ReparacoesMecanico entity)
		{
			this.SendPropertyChanging();
			entity.Mecanico = this;
		}
		
		private void detach_ReparacoesMecanicos(ReparacoesMecanico entity)
		{
			this.SendPropertyChanging();
			entity.Mecanico = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reparacoes")]
	public partial class Reparacoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdMarcacao;
		
		private string _Pecas;
		
		private decimal _CustoTotal;
		
		private System.DateTime _DataInicio;
		
		private System.Nullable<System.DateTime> _DataFim;
		
		private bool _Concluida;
		
		private string _TipoServico;
		
		private EntitySet<ReparacoesMecanico> _ReparacoesMecanicos;
		
		private EntityRef<Marcacoe> _Marcacoe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdMarcacaoChanging(int value);
    partial void OnIdMarcacaoChanged();
    partial void OnPecasChanging(string value);
    partial void OnPecasChanged();
    partial void OnCustoTotalChanging(decimal value);
    partial void OnCustoTotalChanged();
    partial void OnDataInicioChanging(System.DateTime value);
    partial void OnDataInicioChanged();
    partial void OnDataFimChanging(System.Nullable<System.DateTime> value);
    partial void OnDataFimChanged();
    partial void OnConcluidaChanging(bool value);
    partial void OnConcluidaChanged();
    partial void OnTipoServicoChanging(string value);
    partial void OnTipoServicoChanged();
    #endregion
		
		public Reparacoe()
		{
			this._ReparacoesMecanicos = new EntitySet<ReparacoesMecanico>(new Action<ReparacoesMecanico>(this.attach_ReparacoesMecanicos), new Action<ReparacoesMecanico>(this.detach_ReparacoesMecanicos));
			this._Marcacoe = default(EntityRef<Marcacoe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMarcacao", DbType="Int NOT NULL")]
		public int IdMarcacao
		{
			get
			{
				return this._IdMarcacao;
			}
			set
			{
				if ((this._IdMarcacao != value))
				{
					if (this._Marcacoe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMarcacaoChanging(value);
					this.SendPropertyChanging();
					this._IdMarcacao = value;
					this.SendPropertyChanged("IdMarcacao");
					this.OnIdMarcacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pecas", DbType="NVarChar(500)")]
		public string Pecas
		{
			get
			{
				return this._Pecas;
			}
			set
			{
				if ((this._Pecas != value))
				{
					this.OnPecasChanging(value);
					this.SendPropertyChanging();
					this._Pecas = value;
					this.SendPropertyChanged("Pecas");
					this.OnPecasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustoTotal", DbType="Decimal(10,2) NOT NULL")]
		public decimal CustoTotal
		{
			get
			{
				return this._CustoTotal;
			}
			set
			{
				if ((this._CustoTotal != value))
				{
					this.OnCustoTotalChanging(value);
					this.SendPropertyChanging();
					this._CustoTotal = value;
					this.SendPropertyChanged("CustoTotal");
					this.OnCustoTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInicio", DbType="DateTime NOT NULL")]
		public System.DateTime DataInicio
		{
			get
			{
				return this._DataInicio;
			}
			set
			{
				if ((this._DataInicio != value))
				{
					this.OnDataInicioChanging(value);
					this.SendPropertyChanging();
					this._DataInicio = value;
					this.SendPropertyChanged("DataInicio");
					this.OnDataInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataFim", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataFim
		{
			get
			{
				return this._DataFim;
			}
			set
			{
				if ((this._DataFim != value))
				{
					this.OnDataFimChanging(value);
					this.SendPropertyChanging();
					this._DataFim = value;
					this.SendPropertyChanged("DataFim");
					this.OnDataFimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concluida", DbType="Bit NOT NULL")]
		public bool Concluida
		{
			get
			{
				return this._Concluida;
			}
			set
			{
				if ((this._Concluida != value))
				{
					this.OnConcluidaChanging(value);
					this.SendPropertyChanging();
					this._Concluida = value;
					this.SendPropertyChanged("Concluida");
					this.OnConcluidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoServico", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoServico
		{
			get
			{
				return this._TipoServico;
			}
			set
			{
				if ((this._TipoServico != value))
				{
					this.OnTipoServicoChanging(value);
					this.SendPropertyChanging();
					this._TipoServico = value;
					this.SendPropertyChanged("TipoServico");
					this.OnTipoServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reparacoe_ReparacoesMecanico", Storage="_ReparacoesMecanicos", ThisKey="Id", OtherKey="IdReparacao")]
		public EntitySet<ReparacoesMecanico> ReparacoesMecanicos
		{
			get
			{
				return this._ReparacoesMecanicos;
			}
			set
			{
				this._ReparacoesMecanicos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marcacoe_Reparacoe", Storage="_Marcacoe", ThisKey="IdMarcacao", OtherKey="Id", IsForeignKey=true)]
		public Marcacoe Marcacoe
		{
			get
			{
				return this._Marcacoe.Entity;
			}
			set
			{
				Marcacoe previousValue = this._Marcacoe.Entity;
				if (((previousValue != value) 
							|| (this._Marcacoe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marcacoe.Entity = null;
						previousValue.Reparacoes.Remove(this);
					}
					this._Marcacoe.Entity = value;
					if ((value != null))
					{
						value.Reparacoes.Add(this);
						this._IdMarcacao = value.Id;
					}
					else
					{
						this._IdMarcacao = default(int);
					}
					this.SendPropertyChanged("Marcacoe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ReparacoesMecanicos(ReparacoesMecanico entity)
		{
			this.SendPropertyChanging();
			entity.Reparacoe = this;
		}
		
		private void detach_ReparacoesMecanicos(ReparacoesMecanico entity)
		{
			this.SendPropertyChanging();
			entity.Reparacoe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReparacoesMecanicos")]
	public partial class ReparacoesMecanico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdReparacao;
		
		private int _IdMecanico;
		
		private EntityRef<Mecanico> _Mecanico;
		
		private EntityRef<Reparacoe> _Reparacoe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdReparacaoChanging(int value);
    partial void OnIdReparacaoChanged();
    partial void OnIdMecanicoChanging(int value);
    partial void OnIdMecanicoChanged();
    #endregion
		
		public ReparacoesMecanico()
		{
			this._Mecanico = default(EntityRef<Mecanico>);
			this._Reparacoe = default(EntityRef<Reparacoe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReparacao", DbType="Int NOT NULL")]
		public int IdReparacao
		{
			get
			{
				return this._IdReparacao;
			}
			set
			{
				if ((this._IdReparacao != value))
				{
					if (this._Reparacoe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdReparacaoChanging(value);
					this.SendPropertyChanging();
					this._IdReparacao = value;
					this.SendPropertyChanged("IdReparacao");
					this.OnIdReparacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMecanico", DbType="Int NOT NULL")]
		public int IdMecanico
		{
			get
			{
				return this._IdMecanico;
			}
			set
			{
				if ((this._IdMecanico != value))
				{
					if (this._Mecanico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdMecanicoChanging(value);
					this.SendPropertyChanging();
					this._IdMecanico = value;
					this.SendPropertyChanged("IdMecanico");
					this.OnIdMecanicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mecanico_ReparacoesMecanico", Storage="_Mecanico", ThisKey="IdMecanico", OtherKey="Id", IsForeignKey=true)]
		public Mecanico Mecanico
		{
			get
			{
				return this._Mecanico.Entity;
			}
			set
			{
				Mecanico previousValue = this._Mecanico.Entity;
				if (((previousValue != value) 
							|| (this._Mecanico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mecanico.Entity = null;
						previousValue.ReparacoesMecanicos.Remove(this);
					}
					this._Mecanico.Entity = value;
					if ((value != null))
					{
						value.ReparacoesMecanicos.Add(this);
						this._IdMecanico = value.Id;
					}
					else
					{
						this._IdMecanico = default(int);
					}
					this.SendPropertyChanged("Mecanico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reparacoe_ReparacoesMecanico", Storage="_Reparacoe", ThisKey="IdReparacao", OtherKey="Id", IsForeignKey=true)]
		public Reparacoe Reparacoe
		{
			get
			{
				return this._Reparacoe.Entity;
			}
			set
			{
				Reparacoe previousValue = this._Reparacoe.Entity;
				if (((previousValue != value) 
							|| (this._Reparacoe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reparacoe.Entity = null;
						previousValue.ReparacoesMecanicos.Remove(this);
					}
					this._Reparacoe.Entity = value;
					if ((value != null))
					{
						value.ReparacoesMecanicos.Add(this);
						this._IdReparacao = value.Id;
					}
					else
					{
						this._IdReparacao = default(int);
					}
					this.SendPropertyChanged("Reparacoe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veiculos")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Matricula;
		
		private string _Marca;
		
		private string _Modelo;
		
		private int _Ano;
		
		private int _Quilometragem;
		
		private string _Combustivel;
		
		private int _IdCliente;
		
		private EntitySet<Marcacoe> _Marcacoes;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMatriculaChanging(string value);
    partial void OnMatriculaChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnAnoChanging(int value);
    partial void OnAnoChanged();
    partial void OnQuilometragemChanging(int value);
    partial void OnQuilometragemChanged();
    partial void OnCombustivelChanging(string value);
    partial void OnCombustivelChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    #endregion
		
		public Veiculo()
		{
			this._Marcacoes = new EntitySet<Marcacoe>(new Action<Marcacoe>(this.attach_Marcacoes), new Action<Marcacoe>(this.detach_Marcacoes));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matricula", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Matricula
		{
			get
			{
				return this._Matricula;
			}
			set
			{
				if ((this._Matricula != value))
				{
					this.OnMatriculaChanging(value);
					this.SendPropertyChanging();
					this._Matricula = value;
					this.SendPropertyChanged("Matricula");
					this.OnMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano", DbType="Int NOT NULL")]
		public int Ano
		{
			get
			{
				return this._Ano;
			}
			set
			{
				if ((this._Ano != value))
				{
					this.OnAnoChanging(value);
					this.SendPropertyChanging();
					this._Ano = value;
					this.SendPropertyChanged("Ano");
					this.OnAnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quilometragem", DbType="Int NOT NULL")]
		public int Quilometragem
		{
			get
			{
				return this._Quilometragem;
			}
			set
			{
				if ((this._Quilometragem != value))
				{
					this.OnQuilometragemChanging(value);
					this.SendPropertyChanging();
					this._Quilometragem = value;
					this.SendPropertyChanged("Quilometragem");
					this.OnQuilometragemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Combustivel", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Combustivel
		{
			get
			{
				return this._Combustivel;
			}
			set
			{
				if ((this._Combustivel != value))
				{
					this.OnCombustivelChanging(value);
					this.SendPropertyChanging();
					this._Combustivel = value;
					this.SendPropertyChanged("Combustivel");
					this.OnCombustivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veiculo_Marcacoe", Storage="_Marcacoes", ThisKey="Id", OtherKey="IdVeiculo")]
		public EntitySet<Marcacoe> Marcacoes
		{
			get
			{
				return this._Marcacoes;
			}
			set
			{
				this._Marcacoes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Veiculo", Storage="_Cliente", ThisKey="IdCliente", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Veiculos.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Veiculos.Add(this);
						this._IdCliente = value.Id;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = this;
		}
		
		private void detach_Marcacoes(Marcacoe entity)
		{
			this.SendPropertyChanging();
			entity.Veiculo = null;
		}
	}
}
#pragma warning restore 1591
